-- Semilla extendida de respuestas para el chatbot (sin IA)
-- Mantén estas en SQL para poder gestionarlas desde el Dashboard sin redeploy.
insert into public.bot_responses (intent, reply, keywords)
values
  ('politica_cancelacion', 'Las cancelaciones se aceptan hasta 24h antes. Indica fecha/hora y servicio para procesar.', array['cancelación','cancelar','anular','politica','política']),
  ('tolerancia_retraso', 'Tolerancia de retraso: 10 minutos. Pasado ese tiempo, la cita puede reprogramarse según disponibilidad.', array['retraso','tarde','demora','tolerancia']),
  ('facturacion', 'Para facturar, comparte RFC/datos de facturación al momento de la cita o responde este hilo con tus datos.', array['factura','facturación','rfc','comprobante','iva']),
  ('reembolso', 'Reembolsos sujetos a política de cancelación. Indica servicio y fecha para revisar tu solicitud.', array['reembolso','devolución','devolucion','refund']),
  ('estacionamiento', 'Contamos con estacionamiento limitado. Llega con anticipación; si se llena, hay opciones públicas cercanas.', array['estacionamiento','parking','auto']),
  ('accesibilidad', 'Nuestras instalaciones son accesibles. Si requieres apoyo adicional, avísame y lo preparo.', array['acceso','accesibilidad','discapacidad','rampa']),
  ('contacto_directo', 'Puedo escalar tu solicitud a un administrador. Describe tu caso y tu correo.', array['contacto','admin','administrador','humano','soporte']),
  ('recordatorio_config', 'Podemos enviar recordatorios por correo. Si deseas activarlos, confirma tu correo y la cita.', array['recordatorio','recordatorios','avisar','notificación']),
  ('prep_cita', 'Llega 10 minutos antes. Para ciertos servicios podría requerirse ayuno; confirma según el servicio.', array['preparación','preparacion','ayuno','antes de la cita']),
  ('post_cita', 'Después de la cita, sigue las indicaciones del profesional. Si tienes dudas, pregunta y te ayudamos.', array['después','despues','post','cuidados']),
  ('pago_tarjeta', 'Aceptamos tarjeta y pago en línea. Confirma si deseas link de pago o pagar en sitio.', array['tarjeta','visa','mastercard','pagar en línea','pago online']),
  ('pago_efectivo', 'Aceptamos efectivo en recepción. Si prefieres otro método, házmelo saber.', array['efectivo','cash','pagar en efectivo']),
  ('servicio_prioridad', 'Para urgencias o prioridad, indica motivo y servicio; validamos huecos o asignación especial.', array['urgente','prioridad','emergencia']),
  ('servicio_duracion', 'La duración típica es la del servicio elegido; puede variar según caso. ¿Qué servicio necesitas?', array['duración','duracion','cuánto dura','tiempo']),
  ('servicio_requisitos', 'Algunos servicios tienen requisitos previos. Dime el servicio y te comparto requisitos.', array['requisito','requisitos','previo','antes de']),
  ('servicio_documentos', 'Si necesitas traer documentos, te lo indicaremos para cada servicio. ¿Cuál deseas?', array['documento','documentos','papeles']),
  ('servicio_virtual_detalle', 'En consulta virtual se enviará un enlace. Verifica tu correo y conexión estable.', array['virtual','online','remoto','en línea']),
  ('servicio_presencial_detalle', 'En consulta presencial, llega 10 minutos antes y pregunta en recepción por tu profesional.', array['presencial','en sitio','en persona']),
  ('empleado_disponibilidad', 'Indica fecha y servicio para mostrar personal disponible y evitar solapes.', array['disponibilidad','horario doctor','doctor disponible']),
  ('empleado_cambio', 'Si deseas cambiar de profesional, dime tu cita actual y a quién prefieres.', array['cambiar doctor','otro doctor','cambio de médico']),
  ('ubicacion_detalle', 'Nuestra dirección está en tu panel. Si requieres mapa o referencias, indícame.', array['ubicación','direccion','dirección','mapa']),
  ('idioma_es', 'Respondo en español. Si necesitas otro idioma, todavía no está disponible.', array['idioma','language']),
  ('privacidad', 'Tus datos se almacenan en Supabase con políticas RLS; solo roles autorizados acceden.', array['privacidad','datos','rgpd','seguridad']),
  ('chat_historial_detalle', 'Puedo recuperar mensajes previos para contexto. Dime el tema o fecha.', array['historial','conversación','mensajes previos']),
  ('cita_estado', 'Puedo consultar el estado de tu cita (pendiente/confirmada). Dame fecha o ID.', array['estado cita','estatus cita','confirmada']),
  ('cita_proxima', '¿Quieres saber tu próxima cita? Indica tu correo o el rango de fechas.', array['próxima cita','siguiente cita','proxima']),
  ('cita_multiples', 'Si quieres varias citas, agenda una por fecha/servicio para respetar disponibilidad.', array['varias citas','múltiples citas']),
  ('correo_activacion', 'Si tu cuenta está pendiente, espera el correo de activación tras aprobación admin.', array['activación','activar cuenta','pendiente']),
  ('pagos_factura_timing', 'La factura se emite tras confirmar el servicio. Comparte tus datos de facturación.', array['factura','facturacion','facturación']),
  ('ayuda_general', 'Soy un bot de ayuda. Pregúntame sobre citas, servicios, pagos, ubicación o soporte.', array['ayuda','help','soporte']),
  ('fallback_ext', 'No encontré coincidencias. Opciones: "citas", "cancelar cita", "precios", "pagos", "ubicación", "soporte".', array['?']);
